// File generated by FlutterFire CLI from GoogleService-Info.plist and google-services.json.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web. '
        'You can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos. '
          'You can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows. '
          'You can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux. '
          'You can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB-6Vn1WKc3SjAddtO2lf94WmpYDNlaBU',
    appId: '1:294885107607:android:c6f2190f250e76ded386d2',
    messagingSenderId: '294885107607',
    projectId: 'vesperio-c74f9',
    storageBucket: 'vesperio-c74f9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv7XtbPABj2z2vpleqXatNOJx4i5wErv0',
    appId: '1:294885107607:ios:f23d06321c70c393d386d2',
    messagingSenderId: '294885107607',
    projectId: 'vesperio-c74f9',
    storageBucket: 'vesperio-c74f9.firebasestorage.app',
    iosBundleId: 'com.vesperio.app',
  );
}
